# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dawe0049/School/C++/CPPMiniVersionControl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dawe0049/School/C++/CPPMiniVersionControl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawe0049/School/C++/CPPMiniVersionControl/CMakeFiles /home/dawe0049/School/C++/CPPMiniVersionControl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawe0049/School/C++/CPPMiniVersionControl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MiniVersionControl

# Build rule for target.
MiniVersionControl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MiniVersionControl
.PHONY : MiniVersionControl

# fast build rule for target.
MiniVersionControl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/build
.PHONY : MiniVersionControl/fast

#=============================================================================
# Target rules for targets named MiniVersionControl_autogen_timestamp_deps

# Build rule for target.
MiniVersionControl_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MiniVersionControl_autogen_timestamp_deps
.PHONY : MiniVersionControl_autogen_timestamp_deps

# fast build rule for target.
MiniVersionControl_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl_autogen_timestamp_deps.dir/build.make CMakeFiles/MiniVersionControl_autogen_timestamp_deps.dir/build
.PHONY : MiniVersionControl_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MiniVersionControl_autogen

# Build rule for target.
MiniVersionControl_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MiniVersionControl_autogen
.PHONY : MiniVersionControl_autogen

# fast build rule for target.
MiniVersionControl_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl_autogen.dir/build.make CMakeFiles/MiniVersionControl_autogen.dir/build
.PHONY : MiniVersionControl_autogen/fast

MiniVersionControl_autogen/mocs_compilation.o: MiniVersionControl_autogen/mocs_compilation.cpp.o
.PHONY : MiniVersionControl_autogen/mocs_compilation.o

# target to build an object file
MiniVersionControl_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/MiniVersionControl_autogen/mocs_compilation.cpp.o
.PHONY : MiniVersionControl_autogen/mocs_compilation.cpp.o

MiniVersionControl_autogen/mocs_compilation.i: MiniVersionControl_autogen/mocs_compilation.cpp.i
.PHONY : MiniVersionControl_autogen/mocs_compilation.i

# target to preprocess a source file
MiniVersionControl_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/MiniVersionControl_autogen/mocs_compilation.cpp.i
.PHONY : MiniVersionControl_autogen/mocs_compilation.cpp.i

MiniVersionControl_autogen/mocs_compilation.s: MiniVersionControl_autogen/mocs_compilation.cpp.s
.PHONY : MiniVersionControl_autogen/mocs_compilation.s

# target to generate assembly for a file
MiniVersionControl_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/MiniVersionControl_autogen/mocs_compilation.cpp.s
.PHONY : MiniVersionControl_autogen/mocs_compilation.cpp.s

gui/InitRepoDialog.o: gui/InitRepoDialog.cpp.o
.PHONY : gui/InitRepoDialog.o

# target to build an object file
gui/InitRepoDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/InitRepoDialog.cpp.o
.PHONY : gui/InitRepoDialog.cpp.o

gui/InitRepoDialog.i: gui/InitRepoDialog.cpp.i
.PHONY : gui/InitRepoDialog.i

# target to preprocess a source file
gui/InitRepoDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/InitRepoDialog.cpp.i
.PHONY : gui/InitRepoDialog.cpp.i

gui/InitRepoDialog.s: gui/InitRepoDialog.cpp.s
.PHONY : gui/InitRepoDialog.s

# target to generate assembly for a file
gui/InitRepoDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/InitRepoDialog.cpp.s
.PHONY : gui/InitRepoDialog.cpp.s

gui/MainWindow.o: gui/MainWindow.cpp.o
.PHONY : gui/MainWindow.o

# target to build an object file
gui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/MainWindow.cpp.o
.PHONY : gui/MainWindow.cpp.o

gui/MainWindow.i: gui/MainWindow.cpp.i
.PHONY : gui/MainWindow.i

# target to preprocess a source file
gui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/MainWindow.cpp.i
.PHONY : gui/MainWindow.cpp.i

gui/MainWindow.s: gui/MainWindow.cpp.s
.PHONY : gui/MainWindow.s

# target to generate assembly for a file
gui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/MainWindow.cpp.s
.PHONY : gui/MainWindow.cpp.s

gui/SelectRepoDialog.o: gui/SelectRepoDialog.cpp.o
.PHONY : gui/SelectRepoDialog.o

# target to build an object file
gui/SelectRepoDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/SelectRepoDialog.cpp.o
.PHONY : gui/SelectRepoDialog.cpp.o

gui/SelectRepoDialog.i: gui/SelectRepoDialog.cpp.i
.PHONY : gui/SelectRepoDialog.i

# target to preprocess a source file
gui/SelectRepoDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/SelectRepoDialog.cpp.i
.PHONY : gui/SelectRepoDialog.cpp.i

gui/SelectRepoDialog.s: gui/SelectRepoDialog.cpp.s
.PHONY : gui/SelectRepoDialog.s

# target to generate assembly for a file
gui/SelectRepoDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/SelectRepoDialog.cpp.s
.PHONY : gui/SelectRepoDialog.cpp.s

gui/StartingWindow.o: gui/StartingWindow.cpp.o
.PHONY : gui/StartingWindow.o

# target to build an object file
gui/StartingWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/StartingWindow.cpp.o
.PHONY : gui/StartingWindow.cpp.o

gui/StartingWindow.i: gui/StartingWindow.cpp.i
.PHONY : gui/StartingWindow.i

# target to preprocess a source file
gui/StartingWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/StartingWindow.cpp.i
.PHONY : gui/StartingWindow.cpp.i

gui/StartingWindow.s: gui/StartingWindow.cpp.s
.PHONY : gui/StartingWindow.s

# target to generate assembly for a file
gui/StartingWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/gui/StartingWindow.cpp.s
.PHONY : gui/StartingWindow.cpp.s

src/MiniVersionControl.o: src/MiniVersionControl.cpp.o
.PHONY : src/MiniVersionControl.o

# target to build an object file
src/MiniVersionControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/src/MiniVersionControl.cpp.o
.PHONY : src/MiniVersionControl.cpp.o

src/MiniVersionControl.i: src/MiniVersionControl.cpp.i
.PHONY : src/MiniVersionControl.i

# target to preprocess a source file
src/MiniVersionControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/src/MiniVersionControl.cpp.i
.PHONY : src/MiniVersionControl.cpp.i

src/MiniVersionControl.s: src/MiniVersionControl.cpp.s
.PHONY : src/MiniVersionControl.s

# target to generate assembly for a file
src/MiniVersionControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/src/MiniVersionControl.cpp.s
.PHONY : src/MiniVersionControl.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MiniVersionControl.dir/build.make CMakeFiles/MiniVersionControl.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MiniVersionControl_autogen"
	@echo "... MiniVersionControl_autogen_timestamp_deps"
	@echo "... MiniVersionControl"
	@echo "... MiniVersionControl_autogen/mocs_compilation.o"
	@echo "... MiniVersionControl_autogen/mocs_compilation.i"
	@echo "... MiniVersionControl_autogen/mocs_compilation.s"
	@echo "... gui/InitRepoDialog.o"
	@echo "... gui/InitRepoDialog.i"
	@echo "... gui/InitRepoDialog.s"
	@echo "... gui/MainWindow.o"
	@echo "... gui/MainWindow.i"
	@echo "... gui/MainWindow.s"
	@echo "... gui/SelectRepoDialog.o"
	@echo "... gui/SelectRepoDialog.i"
	@echo "... gui/SelectRepoDialog.s"
	@echo "... gui/StartingWindow.o"
	@echo "... gui/StartingWindow.i"
	@echo "... gui/StartingWindow.s"
	@echo "... src/MiniVersionControl.o"
	@echo "... src/MiniVersionControl.i"
	@echo "... src/MiniVersionControl.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

